spring.datasource.url=jdbc:postgresql://localhost:5432/family-budget-db
spring.datasource.username=db-user
spring.datasource.password=gfg
spring.datasource.driver-class-name=org.postgresql.Driver

# ????? ?? ?? ??????????? ? ?? ??????????? ????????? Hibernate, ? ???????? ?????????? Liquibase
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

liquibase.enabled=true
liquibase.drop-first=false
liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
liquibase.default-schema=public
